// <auto-generated />
using System;
using Cdm.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cdm.Migrations.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20251001183524_UpdateCharacterConfiguration")]
    partial class UpdateCharacterConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cdm.Data.Common.Models.CharacterInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ObtainedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("IX_CharacterInventory_CharacterId");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("IX_CharacterInventory_EquipmentId");

                    b.HasIndex("CharacterId", "EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_CharacterInventory_Character_Equipment");

                    b.HasIndex("CharacterId", "IsEquipped")
                        .HasDatabaseName("IX_CharacterInventory_Character_Equipped");

                    b.ToTable("CharacterInventory", (string)null);
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.CharacterSpells", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LearnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.Property<int?>("SpellSlotLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("IX_CharacterSpells_CharacterId");

                    b.HasIndex("SpellId")
                        .HasDatabaseName("IX_CharacterSpells_SpellId");

                    b.HasIndex("CharacterId", "IsPrepared")
                        .HasDatabaseName("IX_CharacterSpells_Character_Prepared");

                    b.HasIndex("CharacterId", "SpellId")
                        .IsUnique()
                        .HasDatabaseName("IX_CharacterSpells_Character_Spell");

                    b.ToTable("CharacterSpells", (string)null);
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ActionSequence")
                        .HasColumnType("int");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("AdvantageType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CombatId")
                        .HasColumnType("int");

                    b.Property<int?>("DamageDealt")
                        .HasColumnType("int");

                    b.Property<string>("DamageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiceRolls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ExecutionTime")
                        .HasColumnType("time");

                    b.Property<string>("GameSpecificData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HealingDone")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<int?>("MovementDistance")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PositionAfter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PositionBefore")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourcesUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("SavingThrow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpellId")
                        .HasColumnType("int");

                    b.Property<int?>("SpellLevel")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CombatId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("TargetId");

                    b.HasIndex("CombatId", "Round");

                    b.ToTable("CombatActions");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<string>("AvailableActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CombatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("int");

                    b.Property<string>("GameSpecificData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Initiative")
                        .HasColumnType("int");

                    b.Property<int>("InitiativeTiebreaker")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConscious")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTurnAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NpcId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("StatusEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("TurnsPlayed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.HasIndex("CombatId", "Initiative");

                    b.HasIndex("CombatId", "ParticipantType");

                    b.ToTable("CombatParticipants");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTurnIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CurrentTurnStarted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TurnOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("TurnTimeLimit")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.HasIndex("SessionId", "Status");

                    b.ToTable("CombatSessions");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatStatusEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppliedAtRound")
                        .HasColumnType("int");

                    b.Property<bool>("CanBeDispelled")
                        .HasColumnType("bit");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InitialDuration")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("bit");

                    b.Property<string>("Modifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("PeriodicEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SavingThrow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SourceParticipantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EffectType");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SourceParticipantId");

                    b.HasIndex("ParticipantId", "IsActive");

                    b.ToTable("CombatStatusEffects");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.EquipmentOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("GameMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TargetPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_EquipmentOffers_CampaignId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("GameMasterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EquipmentOffers_Status");

                    b.HasIndex("TargetPlayerId")
                        .HasDatabaseName("IX_EquipmentOffers_TargetPlayerId");

                    b.HasIndex("CampaignId", "TargetPlayerId", "Status")
                        .HasDatabaseName("IX_EquipmentOffers_Campaign_Player_Status");

                    b.ToTable("EquipmentOffers", (string)null);
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.EquipmentTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("FromPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("ToPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_EquipmentTrades_CampaignId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FromPlayerId")
                        .HasDatabaseName("IX_EquipmentTrades_FromPlayerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EquipmentTrades_Status");

                    b.HasIndex("ToPlayerId")
                        .HasDatabaseName("IX_EquipmentTrades_ToPlayerId");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("IX_EquipmentTrades_Campaign_Status");

                    b.ToTable("EquipmentTrades", (string)null);
                });

            modelBuilder.Entity("Cdm.Data.Models.ACharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHostile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNpc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemCharacter")
                        .HasColumnType("bit");

                    b.Property<int>("Leveling")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId");

                    b.ToTable("ACharacter");

                    b.HasDiscriminator().HasValue("ACharacter");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cdm.Data.Models.AEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Equipment_Category");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Equipment_CreatedByUserId");

                    b.HasIndex("GameType")
                        .HasDatabaseName("IX_Equipment_GameType");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Equipment_Name");

                    b.HasIndex("Category", "GameType")
                        .HasDatabaseName("IX_Equipment_Category_GameType");

                    b.HasIndex("GameType", "IsPublic", "IsActive")
                        .HasDatabaseName("IX_Equipment_GameType_IsPublic_IsActive");

                    b.ToTable("Equipment", (string)null);

                    b.HasDiscriminator().HasValue("AEquipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cdm.Data.Models.ASpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Spells_CreatedByUserId");

                    b.HasIndex("GameType")
                        .HasDatabaseName("IX_Spells_GameType");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Spells_Name");

                    b.HasIndex("GameType", "IsPublic", "IsActive")
                        .HasDatabaseName("IX_Spells_GameType_IsPublic_IsActive");

                    b.ToTable("Spells", (string)null);

                    b.HasDiscriminator().HasValue("ASpell");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cdm.Data.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GameType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("IX_Campaigns_CreatedById");

                    b.HasIndex("GameType")
                        .HasDatabaseName("IX_Campaigns_GameType");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_Campaigns_IsPublic");

                    b.HasIndex("GameType", "IsPublic")
                        .HasDatabaseName("IX_Campaigns_GameType_IsPublic");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Cdm.Data.Models.CampaignInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvitedById")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvitedById");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "Email")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("CampaignInvitations");
                });

            modelBuilder.Entity("Cdm.Data.Models.CampaignParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CampaignParticipants");
                });

            modelBuilder.Entity("Cdm.Data.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("IX_Chapters_CampaignId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Chapters_IsActive");

                    b.HasIndex("CampaignId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_Chapters_CampaignId_Order");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Cdm.Data.Models.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NpcMood")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("IX_ContentBlocks_ChapterId");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("IX_ContentBlocks_CharacterId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_ContentBlocks_Type");

                    b.HasIndex("ChapterId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentBlocks_ChapterId_Order");

                    b.ToTable("ContentBlocks", t =>
                        {
                            t.HasCheckConstraint("CK_ContentBlocks_NpcDialogue", "([Type] = 'NpcDialogue' AND [CharacterId] IS NOT NULL AND [NpcMood] IS NOT NULL) OR ([Type] != 'NpcDialogue' AND [CharacterId] IS NULL AND [NpcMood] IS NULL)");

                            t.HasCheckConstraint("CK_ContentBlocks_Type", "[Type] IN ('Location', 'NpcDialogue', 'Description', 'Event')");
                        });
                });

            modelBuilder.Entity("Cdm.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserEmail");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cdm.Data.Dnd.Models.CharacterDnd", b =>
                {
                    b.HasBaseType("Cdm.Data.Models.ACharacter");

                    b.Property<int>("AdditionalCharism")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalConstitution")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalDexterity")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalIntelligence")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalStrong")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalWisdoms")
                        .HasColumnType("int");

                    b.Property<int>("Charism")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClassArmor")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strong")
                        .HasColumnType("int");

                    b.Property<int>("Wisdoms")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CharacterDnd");
                });

            modelBuilder.Entity("Cdm.Data.Dnd.Models.EquipmentDnd", b =>
                {
                    b.HasBaseType("Cdm.Data.Models.AEquipment");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("int");

                    b.Property<int?>("Charges")
                        .HasColumnType("int");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Effect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArmor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMagical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShield")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeapon")
                        .HasColumnType("bit");

                    b.Property<string>("MagicalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxDexBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Common");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("bit");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("bit");

                    b.Property<int>("StrengthRequirement")
                        .HasColumnType("int");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("ArmorClass")
                        .HasDatabaseName("IX_Equipment_ArmorClass");

                    b.HasIndex("AttackBonus")
                        .HasDatabaseName("IX_Equipment_AttackBonus");

                    b.HasIndex("DamageType")
                        .HasDatabaseName("IX_Equipment_DamageType");

                    b.HasIndex("Rarity")
                        .HasDatabaseName("IX_Equipment_Rarity");

                    b.HasIndex("WeaponType")
                        .HasDatabaseName("IX_Equipment_WeaponType");

                    b.HasIndex("IsWeapon", "IsArmor")
                        .HasDatabaseName("IX_Equipment_Type_Flags");

                    b.HasDiscriminator().HasValue("EquipmentDnd");
                });

            modelBuilder.Entity("Cdm.Data.Dnd.Models.SpellDnd", b =>
                {
                    b.HasBaseType("Cdm.Data.Models.ASpell");

                    b.Property<string>("AttackRoll")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HigherLevelDamage")
                        .HasColumnType("int");

                    b.Property<bool>("IsRitual")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaterialComponent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresConcentration")
                        .HasColumnType("bit");

                    b.Property<string>("SavingThrow")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_Spells_Level");

                    b.HasIndex("School")
                        .HasDatabaseName("IX_Spells_School");

                    b.HasIndex("Level", "School")
                        .HasDatabaseName("IX_Spells_Level_School");

                    b.HasDiscriminator().HasValue("SpellDnd");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.CharacterInventory", b =>
                {
                    b.HasOne("Cdm.Data.Models.ACharacter", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.AEquipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatAction", b =>
                {
                    b.HasOne("Cdm.Data.Common.Models.Combat.CombatParticipant", "Actor")
                        .WithMany("Actions")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Common.Models.Combat.CombatSession", "Combat")
                        .WithMany("Actions")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Common.Models.Combat.CombatParticipant", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actor");

                    b.Navigation("Combat");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatParticipant", b =>
                {
                    b.HasOne("Cdm.Data.Common.Models.Combat.CombatSession", "Combat")
                        .WithMany("Participants")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatSession", b =>
                {
                    b.HasOne("Cdm.Data.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatStatusEffect", b =>
                {
                    b.HasOne("Cdm.Data.Common.Models.Combat.CombatParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Common.Models.Combat.CombatParticipant", "SourceParticipant")
                        .WithMany()
                        .HasForeignKey("SourceParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Participant");

                    b.Navigation("SourceParticipant");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.EquipmentOffer", b =>
                {
                    b.HasOne("Cdm.Data.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.AEquipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.User", "GameMaster")
                        .WithMany()
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.User", "TargetPlayer")
                        .WithMany()
                        .HasForeignKey("TargetPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Equipment");

                    b.Navigation("GameMaster");

                    b.Navigation("TargetPlayer");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.EquipmentTrade", b =>
                {
                    b.HasOne("Cdm.Data.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.AEquipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.User", "FromPlayer")
                        .WithMany()
                        .HasForeignKey("FromPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.User", "ToPlayer")
                        .WithMany()
                        .HasForeignKey("ToPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Equipment");

                    b.Navigation("FromPlayer");

                    b.Navigation("ToPlayer");
                });

            modelBuilder.Entity("Cdm.Data.Models.ACharacter", b =>
                {
                    b.HasOne("Cdm.Data.Models.Chapter", "Chapter")
                        .WithMany("Characters")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cdm.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cdm.Data.Models.AEquipment", b =>
                {
                    b.HasOne("Cdm.Data.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Cdm.Data.Models.ASpell", b =>
                {
                    b.HasOne("Cdm.Data.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Cdm.Data.Models.Campaign", b =>
                {
                    b.HasOne("Cdm.Data.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Cdm.Data.Models.CampaignInvitation", b =>
                {
                    b.HasOne("Cdm.Data.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("InvitedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cdm.Data.Models.CampaignParticipant", b =>
                {
                    b.HasOne("Cdm.Data.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.CampaignInvitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cdm.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Invitation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cdm.Data.Models.Chapter", b =>
                {
                    b.HasOne("Cdm.Data.Models.Campaign", "Campaign")
                        .WithMany("Chapters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Cdm.Data.Models.ContentBlock", b =>
                {
                    b.HasOne("Cdm.Data.Models.Chapter", "Chapter")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cdm.Data.Models.ACharacter", "Character")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatParticipant", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Cdm.Data.Common.Models.Combat.CombatSession", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Cdm.Data.Models.ACharacter", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("Cdm.Data.Models.Campaign", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Cdm.Data.Models.Chapter", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ContentBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
